### ISSUE TITLE
Update search for DCC needs

### ISSUE THREAD

**Issue by mewtaylor** [dot-comm-care/dot-comm-care-needs-offers#2]
Needs & offers are each specified in one field via comma-delineation. Consequently, it'd be helpful to be able to search those fields for types of requests/offers.

**Comment by esetnik** [comment]
I pushed a fix, but i'm not a maintainer so I can't mark you as a reviewer on the PR.

**Comment by mewtaylor** [comment]
@esetnik whoops lemme change that
